### ISSUE TITLE
Info about `as` keyword

### ISSUE THREAD

**Issue by fredcy** [izdi/elm-cheat-sheet#1]
Very nice resource. May I suggest adding a brief section about the `as` keyword that can create aliases for values. Here is a contrived / useless example:

```
tupleadd i ((x, y) as t) =
    if i > 0 then (x + i, y + i) else t
```

**Comment by izdi** [comment]
@fredcy Thanks for suggestion.
I still add sections and categories, I'm thinking to put this keyword into the operators section ->  `other` category. Adding whole section/category for a single keyword is questionable, don't you think?
To be honest I have not thought of using `as` this way, and I have not found any information concerning this way in standard library. Only in case of importing modules _as something_.

I appreciate the effort :octocat:

**Comment by fredcy** [comment]
Sorry, I didn't mean "section" as literally a separate document section. 

I haven't seen `as` formally defined either. I noticed it while browsing some of Evan's code. He used it in a recent posting too: https://groups.google.com/d/msg/elm-discuss/TLy84m-4u3w/7E-YyopNEQAJ

**Comment by izdi** [comment]
Added [here](https://github.com/izdi/elm-cheat-sheet/commit/99b7afdb97dee201a2f53b973d06173499af96d7#diff-04c6e90faac2675aa89e2176d2eec7d8R667)

Thanks!

**Comment by dcecile** [comment]
@izdi 🤔 Can `as` be used in the context of normal expressions? I see that it's grouped with the `++` and `::` under "Other Operators", and marked with an `a -> a` type signature.

So far I've only seen `as` being used in pattern matching contexts: function variables, lambda variables, let variables, case conditions...

```elm
import Html exposing (text)

f1 ({ a } as x) = x.a + a
f2 = \({ a } as x) -> x.a + a
f3 x = let ({ a } as y) = x in y.a + a
f4 x = case x of ({ a } as y) -> x.a + a

main = [ f1, f2, f3, f4 ]
  |> List.map (\f -> f { a = 3 })
  |> toString
  |> text
```

**Comment by frou** [comment]
@dcecile I guess the missing word is destructuring. This `as` seems like an accoutrement of destructuring, rather than a general operator.

**Comment by aesyondu** [comment]
I'm trying to find official documentation about the `as` keyword. I've noted that in the Elm in Action book, [there is a line using it](https://github.com/rtfeldman/elm-in-action/compare/4.2.3...4.3.1#diff-404b660c93c70871077640a32d7c4902R144). However there doesn't seem to be any official documentation for it.

I tried using in the elm repl:
```elm
I got stuck on this reserved word:

4|   (1, 2) as t
            ^^
The name `as` is reserved, so try using a different name?
```

Can it only be used in destructuring?
